name: learn_storage
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Cupertino Icons:
  cupertino_icons: ^1.0.2

  #Shared Preference
  shared_preferences: ^2.2.0

  #Lottie
  lottie: ^2.6.0

  #Date Time
  date_time: ^0.10.0

  #Intl
  intl: ^0.18.1
  easy_localization: ^3.0.3
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Flutter Lints
  flutter_lints: ^2.0.0

  #Build Runner
  build_runner: ^2.4.6



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/languages/


