name: learn_storage
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Cupertino Icons:
  cupertino_icons: ^1.0.2

  #Shared Preference
  shared_preferences: ^2.2.0

  #Http
  http: ^1.1.0

  #Json Annotation
  json_annotation: ^4.8.1

  #Freezed
  freezed: ^2.4.1

  #Freezed Annotation
  freezed_annotation: ^2.4.1

  #Lottie
  lottie: ^2.5.0

  #Date Time
  date_time: ^0.10.0

  #Intl
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Flutter Lints
  flutter_lints: ^2.0.0

  #Build Runner
  build_runner: ^2.4.6

  #Json Serializable
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/


